security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_STUDENT:     ROLE_USER
        ROLE_TUTOR:       ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_TUTOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main_provider:
            users:
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                student: { password: studentpass, roles: [ 'ROLE_STUDENT' ] }
                tutor: { password: tutorpass, roles: [ 'ROLE_TUTOR' ] }
#            entity: { class: Bdx\TutoratBundle\Entity\User,
#                      property: username,
#                      roles: [ 'ROLE_USER' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /hello
            anonymous: ~

    access_control:
        - { path: ^/student, roles: [ 'ROLE_TUTOR' ] }
        - { path: ^/tutor, roles: [ 'ROLE_ADMIN' ] }
        - { path: ^/lesson, roles: [ 'ROLE_ADMIN' ] }
