security:
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_STUDENT:     ROLE_USER
        ROLE_TUTOR:       ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main_provider:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        main:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /hello
            anonymous: ~

    access_control:
        - { path: ^/user, roles: [ 'ROLE_ADMIN' ] }
        - { path: ^/student, roles: [ 'ROLE_ADMIN', 'ROLE_TUTOR' ] }
        - { path: ^/tutor, roles: [ 'ROLE_ADMIN' ] }
        - { path: ^/lesson, roles: [ 'ROLE_ADMIN' ] }
