BdxTutoratBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BdxTutoratBundle:Default:index, name : "World" }

BdxTutoratBundle_tutor:
    resource: "@BdxTutoratBundle/Resources/config/routing/tutor.yml"
    prefix:   /tutor

BdxTutoratBundle_lesson:
    resource: "@BdxTutoratBundle/Resources/config/routing/lesson.yml"
    prefix:   /lesson
