parameters:
#    bdx_tutorat.example.class: Bdx\TutoratBundle\Example

services:
#    bdx_tutorat.example:
#        class: %bdx_tutorat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
