parameters:
    gcalendar.class: Bdx\TutoratBundle\GCalendar

services:
    gcalendar:
        class: %gcalendar.class%
        arguments:
            - @session
            - @request
            - %gcalendar.login%
            - %gcalendar.password%
            - %gcalendar.calendarId%
            - %gcalendar.calendarCookie%
